### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NdaruAjaa** [nhanaz-pm-pl/BackgroundMusic#1]
PocketMine-MP version: 5.3.2 [Protocol 594]
Git commit: 69abd5eb532b850c031b0d5529993edd2e591c83
PHP version: 8.1.20
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BackgroundMusic

Error: Class "NhanAZ\libRegRsp\libRegRsp" not found
File: plugins/BackgroundMusic-master/src/NhanAZ/BackgroundMusic/Main
Line: 20
Type: Error
Backtrace:
#0 pmsrc/src/plugin/PluginBase(118): NhanAZ\BackgroundMusic\Main->onEnable()
#1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#2 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object NhanAZ\BackgroundMusic\Main#41547)
#3 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41377)
#4 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#5 pmsrc/src/PocketMine(357): pocketmine\server()
#6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by NhanAZ** [comment]
Please install libRegRsp library
